//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace lingualink_client.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("lingualink_client.Properties.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Add Language 的本地化字符串。
        /// </summary>
        internal static string AddLanguage {
            get {
                return ResourceManager.GetString("AddLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Clear Log 的本地化字符串。
        /// </summary>
        internal static string ClearLog {
            get {
                return ResourceManager.GetString("ClearLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enable OSC Sending 的本地化字符串。
        /// </summary>
        internal static string EnableOsc {
            get {
                return ResourceManager.GetString("EnableOsc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Interface Language 的本地化字符串。
        /// </summary>
        internal static string InterfaceLanguage {
            get {
                return ResourceManager.GetString("InterfaceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Log 的本地化字符串。
        /// </summary>
        internal static string Log {
            get {
                return ResourceManager.GetString("Log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Maximum Voice Duration (seconds) 的本地化字符串。
        /// </summary>
        internal static string MaxVoiceDuration {
            get {
                return ResourceManager.GetString("MaxVoiceDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Minimum Voice Duration (seconds) 的本地化字符串。
        /// </summary>
        internal static string MinVoiceDuration {
            get {
                return ResourceManager.GetString("MinVoiceDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Minimum Recording Volume Threshold (0-100%) 的本地化字符串。
        /// </summary>
        internal static string MinVolumeThreshold {
            get {
                return ResourceManager.GetString("MinVolumeThreshold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OSC IP Address 的本地化字符串。
        /// </summary>
        internal static string OscIpAddress {
            get {
                return ResourceManager.GetString("OscIpAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OSC Port 的本地化字符串。
        /// </summary>
        internal static string OscPort {
            get {
                return ResourceManager.GetString("OscPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Play Notification Sound 的本地化字符串。
        /// </summary>
        internal static string PlayNotificationSound {
            get {
                return ResourceManager.GetString("PlayNotificationSound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Refresh 的本地化字符串。
        /// </summary>
        internal static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Remove 的本地化字符串。
        /// </summary>
        internal static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Running Log 的本地化字符串。
        /// </summary>
        internal static string RunningLog {
            get {
                return ResourceManager.GetString("RunningLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save 的本地化字符串。
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select Microphone 的本地化字符串。
        /// </summary>
        internal static string SelectMicrophone {
            get {
                return ResourceManager.GetString("SelectMicrophone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Send Immediately (Bypass Keyboard) 的本地化字符串。
        /// </summary>
        internal static string SendImmediately {
            get {
                return ResourceManager.GetString("SendImmediately", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Server URL 的本地化字符串。
        /// </summary>
        internal static string ServerUrl {
            get {
                return ResourceManager.GetString("ServerUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Service 的本地化字符串。
        /// </summary>
        internal static string Service {
            get {
                return ResourceManager.GetString("Service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Settings 的本地化字符串。
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Silence Detection Threshold (seconds) 的本地化字符串。
        /// </summary>
        internal static string SilenceThreshold {
            get {
                return ResourceManager.GetString("SilenceThreshold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Start 的本地化字符串。
        /// </summary>
        internal static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Updates 的本地化字符串。
        /// </summary>
        internal static string UpdateSettings {
            get {
                return ResourceManager.GetString("UpdateSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Current Version 的本地化字符串。
        /// </summary>
        internal static string UpdateCurrentVersion {
            get {
                return ResourceManager.GetString("UpdateCurrentVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Latest Version 的本地化字符串。
        /// </summary>
        internal static string UpdateLatestVersion {
            get {
                return ResourceManager.GetString("UpdateLatestVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Check for Updates 的本地化字符串。
        /// </summary>
        internal static string UpdateCheckButton {
            get {
                return ResourceManager.GetString("UpdateCheckButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Download and Update 的本地化字符串。
        /// </summary>
        internal static string UpdateDownloadButton {
            get {
                return ResourceManager.GetString("UpdateDownloadButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Download progress 的本地化字符串。
        /// </summary>
        internal static string UpdateDownloadProgress {
            get {
                return ResourceManager.GetString("UpdateDownloadProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Not checked yet 的本地化字符串。
        /// </summary>
        internal static string UpdateStatusNotChecked {
            get {
                return ResourceManager.GetString("UpdateStatusNotChecked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Checking... 的本地化字符串。
        /// </summary>
        internal static string UpdateStatusChecking {
            get {
                return ResourceManager.GetString("UpdateStatusChecking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Up to date 的本地化字符串。
        /// </summary>
        internal static string UpdateStatusUpToDate {
            get {
                return ResourceManager.GetString("UpdateStatusUpToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Check failed 的本地化字符串。
        /// </summary>
        internal static string UpdateStatusFailed {
            get {
                return ResourceManager.GetString("UpdateStatusFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Updates unavailable in this build 的本地化字符串。
        /// </summary>
        internal static string UpdateStatusUnavailable {
            get {
                return ResourceManager.GetString("UpdateStatusUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to check for updates 的本地化字符串。
        /// </summary>
        internal static string UpdateErrorCheck {
            get {
                return ResourceManager.GetString("UpdateErrorCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Update downloaded. Restart now to apply? 的本地化字符串。
        /// </summary>
        internal static string UpdateDialogDownloadPrompt {
            get {
                return ResourceManager.GetString("UpdateDialogDownloadPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Update Ready 的本地化字符串。
        /// </summary>
        internal static string UpdateReadyTitle {
            get {
                return ResourceManager.GetString("UpdateReadyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to download update 的本地化字符串。
        /// </summary>
        internal static string UpdateErrorDownload {
            get {
                return ResourceManager.GetString("UpdateErrorDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error 的本地化字符串。
        /// </summary>
        internal static string UpdateErrorTitle {
            get {
                return ResourceManager.GetString("UpdateErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No release notes available. 的本地化字符串。
        /// </summary>
        internal static string UpdateNotesUnavailable {
            get {
                return ResourceManager.GetString("UpdateNotesUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unknown 的本地化字符串。
        /// </summary>
        internal static string UpdateVersionUnknown {
            get {
                return ResourceManager.GetString("UpdateVersionUnknown", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Undo Changes 的本地化字符串。
        /// </summary>
        internal static string UndoChanges {
            get {
                return ResourceManager.GetString("UndoChanges", resourceCulture);
            }
        }
    }
}




