//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace lingualink_client.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Lang_ja {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang_ja() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("lingualink_client.Properties.Lang.ja", typeof(Lang_ja).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   アカウント に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Account {
            get {
                return ResourceManager.GetString("Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アカウント設定 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AccountSettings {
            get {
                return ResourceManager.GetString("AccountSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   言語を追加 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AddLanguage {
            get {
                return ResourceManager.GetString("AddLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   テンプレートを追加 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AddTemplate {
            get {
                return ResourceManager.GetString("AddTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   高度なオプション に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AdvancedOptions {
            get {
                return ResourceManager.GetString("AdvancedOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   API認証 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ApiAuthentication {
            get {
                return ResourceManager.GetString("ApiAuthentication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   APIキー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ApiKey {
            get {
                return ResourceManager.GetString("ApiKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   LinguaLink - クライアント に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   VRChat LinguaLink - クライアント に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AppTitleBar {
            get {
                return ResourceManager.GetString("AppTitleBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   音声エンコーディング に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AudioEncoding {
            get {
                return ResourceManager.GetString("AudioEncoding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   音声処理 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AudioProcessing {
            get {
                return ResourceManager.GetString("AudioProcessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   帯域幅使用量を最適化するための音声エンコーディングオプションを構成します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AudioProcessingHint {
            get {
                return ResourceManager.GetString("AudioProcessingHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   リスニング中に致命的なエラーが発生しました：{0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AudioStatusFatalError {
            get {
                return ResourceManager.GetString("AudioStatusFatalError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   リスニング中... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AudioStatusListening {
            get {
                return ResourceManager.GetString("AudioStatusListening", resourceCulture);
            }
        }
        
        /// <summary>
        ///   音声セグメントが短すぎます、無視されました。リスニング中... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AudioStatusSegmentTooShort {
            get {
                return ResourceManager.GetString("AudioStatusSegmentTooShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   無音を検出しました、処理の準備中... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AudioStatusSilenceDetectedProcess {
            get {
                return ResourceManager.GetString("AudioStatusSilenceDetectedProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   音声を検出しました... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AudioStatusSpeechDetected {
            get {
                return ResourceManager.GetString("AudioStatusSpeechDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   音声を検出しました（分割）... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AudioStatusSpeechDetectedSplit {
            get {
                return ResourceManager.GetString("AudioStatusSpeechDetectedSplit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   リスニング開始に失敗しました：{0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AudioStatusStartFailed {
            get {
                return ResourceManager.GetString("AudioStatusStartFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   認証モード に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AuthenticationMode {
            get {
                return ResourceManager.GetString("AuthenticationMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   利用可能なプレースホルダー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AvailablePlaceholders {
            get {
                return ResourceManager.GetString("AvailablePlaceholders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   バックエンドサービス接続 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string BackendServiceConnection {
            get {
                return ResourceManager.GetString("BackendServiceConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   LinguaLink翻訳サーバーへの接続設定を構成します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string BackendServiceConnectionHint {
            get {
                return ResourceManager.GetString("BackendServiceConnectionHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ログをクリア に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ClearLog {
            get {
                return ResourceManager.GetString("ClearLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   近日公開 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ComingSoon {
            get {
                return ResourceManager.GetString("ComingSoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   接続テスト に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConnectionTest {
            get {
                return ResourceManager.GetString("ConnectionTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アカウントを作成 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CreateAccount {
            get {
                return ResourceManager.GetString("CreateAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   テンプレート内容 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CustomTemplateText {
            get {
                return ResourceManager.GetString("CustomTemplateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   カスタムサービス に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CustomService {
            get {
                return ResourceManager.GetString("CustomService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   カスタムサーバー設定 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CustomServerSettings {
            get {
                return ResourceManager.GetString("CustomServerSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   カスタムURLとAPIキーで独自のLinguaLinkサーバーに接続します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CustomServiceHint {
            get {
                return ResourceManager.GetString("CustomServiceHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   英語 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DefaultEnglishLanguageName {
            get {
                return ResourceManager.GetString("DefaultEnglishLanguageName", resourceCulture);
            }
        }
    }
}
